### PR TITLE
Fix git unsafe path in docker

### PR DESCRIPTION
**Pull request by thealgirdas**
related https://github.blog/2022-04-12-git-security-vulnerability-announced/

### CODE REVIEW

**Comment by thealgirdas** [comment]
https://github.com/argyle-systems/argyle-k8s/blob/8262e7fc714710987e90ce862f78bac33f961e3e/.github/workflows/bump-automerge.yaml#L25

**Comment by romanzipp** [comment]
Hey! Are you aware if there's any way to use a forked action in a workflow without publishing it to the marketplace?

**Comment by thealgirdas** [comment]
> https://github.com/argyle-systems/argyle-k8s/blob/8262e7fc714710987e90ce862f78bac33f961e3e/.github/workflows/bump-automerge.yaml#L25

@romanzipp you can use it as a specific commit, like this:
```
    - name: Merge and delete
      uses: argyle-engineering/merge-pull-request@71145704b4fa755be01cb3fefea73b450b820895
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

But as a disclaimer, please don't depend on our repo for any critical tasks.

And let's hope the upstream will merge their PR soon :)

**Comment by romanzipp** [comment]
Thanks! Of course I'll take my own fork till the PR has been approved. (The link above actually leads to a private repo, that's why I asked 😄)

**Pull request merged**
